.TH ltl-actus 1 "20 Feb 2024" ltl-actus "ltl-actus manual"
.SH NAME
ltl-actus \- Linear temporal logic to execute the algorithmic contract types unified standard
.SH SYNOPSIS
ltl-actus
.SH DESCRIPTION
Linear temporal logic to execute the algorithmic contract types unified standard
.SH OPTIONS

.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Quinn Dougherty (quinn@casper.network)
