name: check & build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build-rs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: System Info
        run: |
          uname -a
          nix --version
      - name: Build workspace
        run: nix build -L --no-link --show-trace .#ltl_actus_cli-release
  build-c: 
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: System Info
        run: | 
          uname -a
          nix --version
      - name: Build workspace
        run: nix build -L --no-link --show-trace .#cmake
  check-all:
    runs-on: ${{ matrix.os }}
    needs: build-rs
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Format Check
        if: matrix.os == 'ubuntu-latest'
        run: nix build .#checks.x86_64-linux.treefmt
      - name: Nix Flake Check
        run: nix flake check -L --show-trace

  comms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build January 2024 ACTUS workshop talk
        run: nix build -L --no-link --show-trace .#talk
      - name: Build .docx for February 2024 blog post
        run: nix build -L --no-link --show-trace .#article
